//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        // Primitive properties
    
        public int Id { get; set; }
        public string DateCreated { get; set; }
        public string Content { get; set; }
        public int PostId { get; set; }
    
        // Navigation properties
    
        public virtual Post Post { get; set; }
    
    }
}
