//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        // Primitive properties
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Content { get; set; }
        public int BlogId { get; set; }
    
        // Navigation properties
    
        public virtual Blog Blog { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    
    }
}
